# Generated by Django 2.2.5 on 2020-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('cv_store', models.TextField(blank=True, default='')),
                ('cafe', models.TextField(blank=True, default='')),
                ('lounge', models.TextField(blank=True, default='')),
                ('portal', models.TextField(blank=True, default='')),
                ('department', models.TextField(blank=True, default='')),
                ('one_line', models.TextField(blank=True, default='')),
                ('cafeteria', models.TextField(blank=True, default='')),
            ],
        ),
    ]
