# Generated by Django 2.2.5 on 2020-07-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='portal_video',
            field=models.TextField(blank=True, default=''),
        ),
    ]
