# Generated by Django 2.2.5 on 2020-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_building_portal_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
