# Generated by Django 2.2.10 on 2020-07-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
