# Generated by Django 2.2.5 on 2020-07-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Building')),
            ],
        ),
    ]
